name: cr_flutter_libserialport
description: A simple wrapper around libserialport utilizing Flutter's
  build system to build and deploy the C-library for the target platform.
version: 0.3.0+3
homepage: https://github.com/jpnurmi/flutter_libserialport
repository: https://github.com/jpnurmi/flutter_libserialport
issue_tracker: https://github.com/jpnurmi/flutter_libserialport/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  crlibserialport: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: CrFlutterLibserialportPlugin
      macos:
        pluginClass: CrFlutterLibserialportPlugin
      windows:
        pluginClass: CrFlutterLibserialportPlugin
